import { createApp } from 'vue';
import App from './App.vue';
import { mountRouter } from '@/router';
import { createPinia } from 'pinia';
import piniaPluginPersistedstate from 'pinia-plugin-persistedstate';
const app = createApp(App);
const pinia = createPinia();
pinia.use(piniaPluginPersistedstate);
mountRouter(app);
app.use(pinia);
app.mount('#app');
