import { createApp } from 'vue';
import App from './App.vue';
import '@/assets/styles/tailwind.css';
import { mountRouter } from '@/router';
import { createPinia } from 'pinia';
import piniaPluginPersistedstate from 'pinia-plugin-persistedstate';
import i18n from './locale';
const app = createApp(App);
app.config.globalProperties.$i18n = i18n;
const pinia = createPinia();
pinia.use(piniaPluginPersistedstate);
mountRouter(app);
app.use(pinia);
app.use(i18n);
app.mount('#app');
